baseURL: https://nullpointerbay.com/
languageCode: en-us
title: nullpointerbay.com - Rafal Wachol's Blog 
theme: "PaperMod"

params:
    defaultTheme: auto

    homeInfoParams:
        Title: Hello! 
        Content: > 
            Welcome to my blog. I plan to upload posts about problems encountered while developing apps.
            - I am fan of Flutter ğŸ¦, Linux ğŸ§, mechanical keyboards âŒ¨ and 3d printers ğŸ–¨


            - Feel free to contact me in any of those languages:  ğŸ‡µğŸ‡±ğŸ‡¯ğŸ‡µ ğŸ‡ºğŸ‡¸

    socialIcons:
        - name: github
          url: "https://github.com/charafau"
        - name: twitter
          url: "https://twitter.com/rafalwachol"
        - name: RsS
          url: "index.xml"
    outputs:
        home:
            - HTML
            - RSS
            - JSON

    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowReadingTime: true
